apiVersion: v1
kind: Service
metadata:
  name: dbz-connect
  namespace: kafka
spec:
  selector:
    app: dbz-connect
  ports:
    - name: dbz-connect
      port: 8083
      targetPort: dbz-connect
      protocol: TCP
  type: ClusterIP