FROM postgres:12.4
# note initialization files will be executed in sorted name order as defined by the current locale, which defaults to en_US.utf8. 
# COPY ./ops/dev-stack/tta_postgres/config/database/ .
# RUN psql -h localhost -U postgres -d postgres -f /production.2023.01.06.sql


