FROM debezium/connect:2.2.0.Final
ARG AIVEN_KAFKA_CONNECT_S3_VERSION=2.12.1
USER kafka

# RUN curl --create-dirs -LO --output-dir /tmp/connector https://github.com/aiven/s3-connector-for-apache-kafka/releases/download/v2.12.1/s3-connector-for-apache-kafka-2.12.1.zip && \
RUN curl --create-dirs -LO --output-dir /tmp/connector https://github.com/aiven/s3-connector-for-apache-kafka/releases/download/v${AIVEN_KAFKA_CONNECT_S3_VERSION}/s3-connector-for-apache-kafka-${AIVEN_KAFKA_CONNECT_S3_VERSION}.zip && \
    unzip -o /tmp/connector/s3-connector-for-apache-kafka-${AIVEN_KAFKA_CONNECT_S3_VERSION}.zip -d /tmp/connector && \
    mv "/tmp/connector/s3-connector-for-apache-kafka-${AIVEN_KAFKA_CONNECT_S3_VERSION}" /kafka/connect/s3-connector-for-apache-kafka && \
    rm "/tmp/connector/s3-connector-for-apache-kafka-${AIVEN_KAFKA_CONNECT_S3_VERSION}.zip"
EXPOSE 8083